export const ADD_PROJECT = 'ADD_PROJECT'
export type ADD_PROJECT = typeof ADD_PROJECT

export const ADD_PROJECT_ITEM = 'ADD_PROJECT_ITEM'
export type ADD_PROJECT_ITEM = typeof ADD_PROJECT_ITEM

export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export type REMOVE_PROJECT = typeof REMOVE_PROJECT

export const REMOVE_PROJECT_ITEM = 'REMOVE_PROJECT_ITEM'
export type REMOVE_PROJECT_ITEM = typeof REMOVE_PROJECT_ITEM

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export type UPDATE_PROJECT = typeof UPDATE_PROJECT

export const UPDATE_PROJECT_ITEM = 'UPDATE_PROJECT_ITEM'
export type UPDATE_PROJECT_ITEM = typeof UPDATE_PROJECT_ITEM

export const EDIT_TEMPLATE = 'EDIT_TEMPLATE'
export type EDIT_TEMPLATE = typeof EDIT_TEMPLATE

export const IMPORT_STORE = 'IMPORT_STORE'
export type IMPORT_STORE = typeof IMPORT_STORE